name: Linux

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    ubuntu-latest:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-versions: [ '7.2', '7.3' ]
                coverage: [none]
                include:
                    -   php-versions: '7.4'
                        coverage: xdebug
                    -   php-versions: '8.0'
                        experimental: true
            fail-fast: false

        name: PHP ${{ matrix.php-versions }} on ubuntu-latest

        steps:
            -   name: PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: ${{ matrix.coverage }}

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Configure
                run: cp resources/configurations/ci/.github.php.dist .atoum.php

            -   name: Run
                run: bin/atoum -ebpc
